### PR TITLE
[check-log] Add check-first option and skip the log file on the first run on default

### PR DESCRIPTION
**Pull request by edangelion**

### CODE REVIEW

**Comment by mattn** [comment]
IMO, this should be default behavior. And flag name should be failfirst or something.

**Comment by mattn** [comment]
As far as I think, most of users expect -skipfirst=true in default. For example, the case that restart system after errors something raised. user doesn't want to see duplicated alarms, I think.

**Comment by itchyny** [comment]
Thanks, we'll reconsider the spec.

**Comment by itchyny** [comment]
LGTM!

**Comment by mattn** [comment]
LGTM :+1:

**Pull request merged**
