### PR TITLE
Mysql checks

### PR DESCRIPTION
**Pull request by hiroakis**
I'd like to add two plugins to official.

* check-mysql-connection
  - Checks the number of connections.
* check-mysql-replication
  - Checks the replication status and its Second Behind Master.

These plugins are from my repository.

https://github.com/hiroakis/mackerel-agent-checks-plugins
 * mackerel-check-mysql-connection
 * mackerel-check-mysql-replication

These plugins have been working on our production environment for several months.
If these are useful for people, please add.

### CODE REVIEW

**Comment by Songmu** [comment]
Thank you! I'll take a look. Please wait.

**Comment by Songmu** [comment]
Nice! Can I adjust code to fit our styles after merging?

**Comment by hiroakis** [comment]
sure! 🙆

**Comment by Songmu** [comment]
At #20 I added `check-mysql` which includes your `mysql-check-replication` and `mysql-check-connection` as subcommands.

Thank you for contribution.

**Comment by hiroakis** [comment]
Great work! Thank you for your merging and refactoring.

**Pull request merged**
