### PR TITLE
[check-tcp] add -W option

### PR DESCRIPTION
**Pull request by dozen**
I Added -W option in order to suppress CRITICAL when error occurred.

-W sets the exit status at error occurrence to WARNING.

In the case of request succeeded, evaluation result of -c option eval takes priority.

### CODE REVIEW

**Comment by dozen** [comment]
I erased the branch by mistake.
I will repoen 🙇

**Comment by Songmu** [comment]
Good pull request!

Could you rename `--err-warning` to `--error-warning`? Because it is a policy not to use abbreviations in the long option on check plugins.

**Comment by dozen** [comment]
I agree. Fixed.

**Comment by Songmu** [comment]
Thank you!

**Pull request merged**
